// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioApi.Data;

#nullable disable

namespace PortfolioApi.Migrations
{
    [DbContext(typeof(PortfolioContext))]
    partial class PortfolioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("PortfolioApi.Models.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Certifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "2022",
                            Description = "Certification en cybersécurité éthique et tests de pénétration IoT.",
                            Issuer = "Certification",
                            Name = "Introduction to Ethical Hacking and IOT Cybersecurity / IOT Equipment Penetration Test"
                        },
                        new
                        {
                            Id = 2,
                            Date = "2022",
                            Description = "Participation et certification au hackathon Cybersecurity & Smart Factory.",
                            Issuer = "Hackathon",
                            Name = "Cybersecurity & Smart Factory – Hackathon .01"
                        },
                        new
                        {
                            Id = 3,
                            Date = "2022",
                            Description = "Certification Python orientée data science.",
                            Issuer = "Online Platform",
                            Name = "Python for Data Science"
                        },
                        new
                        {
                            Id = 4,
                            Date = "2022",
                            Description = "Formation aux premiers secours.",
                            Issuer = "Club CRT-ISIMS",
                            Name = "First Aid Training"
                        },
                        new
                        {
                            Id = 5,
                            Date = "2022",
                            Description = "Certification en marketing digital.",
                            Issuer = "CLUB-Tunivision-ESSTHS",
                            Name = "Digital Marketing"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Models.CommunityActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CommunityActivities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = "Aujourd'hui",
                            Order = 1,
                            Organization = "Junior Chamber International Tunisia",
                            Role = "Vice-Président",
                            StartDate = "Janvier 2023"
                        },
                        new
                        {
                            Id = 2,
                            EndDate = "Décembre 2022",
                            Order = 2,
                            Organization = "Junior Chamber International Tunisia",
                            Role = "Secrétaire Général",
                            StartDate = "Janvier 2021"
                        },
                        new
                        {
                            Id = 3,
                            EndDate = "Novembre 2021",
                            Order = 3,
                            Organization = "Tunisian Red Crescent-Club ISIMS",
                            Role = "Trésorier",
                            StartDate = "Novembre 2020"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Models.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = "Software Engineering",
                            Description = "Formation en ingénierie logicielle avec spécialisation en développement fullstack et technologies modernes.",
                            EndDate = "En cours",
                            Institution = "Institute of Advanced Sciences and Technology",
                            Location = "Sfax, Tunisia",
                            Order = 1,
                            StartDate = "Septembre 2023"
                        },
                        new
                        {
                            Id = 2,
                            Degree = "Licence en Informatique – Big Data & Data Analysis",
                            Description = "Licence spécialisée en Big Data et analyse de données.",
                            EndDate = "Juin 2023",
                            Institution = "Higher Institute of Computer Science and Multimedia (ISIMS)",
                            Location = "Sfax, Tunisia",
                            Order = 2,
                            StartDate = "Septembre 2020"
                        },
                        new
                        {
                            Id = 3,
                            Degree = "Baccalauréat en Sciences Expérimentales",
                            Description = "Baccalauréat dans la filière sciences expérimentales.",
                            EndDate = "Juillet 2020",
                            Institution = "Lycée Menzel Hayet Monastir",
                            Location = "Manzel Hayet, Tunisia",
                            Order = 3,
                            StartDate = "Septembre 2019"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Models.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Technologies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "DigitalClick",
                            Description = "Développement et maintenance de modules Odoo. Gestion des ERP, CRM, Achat, Ventes, Comptabilité et Inventaire.",
                            EndDate = "",
                            IsCurrent = true,
                            Location = "Safaqis, SF, Tunisia",
                            Order = 1,
                            StartDate = "Avril 2025",
                            Technologies = "Python, Odoo, XML, ERP, CRM",
                            Title = "Odoo/Python Developer"
                        },
                        new
                        {
                            Id = 2,
                            Company = "Digital Click",
                            Description = "Développement fullstack avec ASP.NET MVC, SSMS, Entity Framework, Identity et Nuget. Intégration de WordPress, Elementor, WPbakery, SEO, WooCommerce, Brevo et Mailchimp.",
                            EndDate = "Avril 2025",
                            IsCurrent = false,
                            Location = "Sfax, Tunisia",
                            Order = 2,
                            StartDate = "Novembre 2024",
                            Technologies = "ASP.NET, MVC, SSMS, Entity Framework, GIT, DEVEXTREAM, WordPress, Elementor, SEO, WooCommerce",
                            Title = "Fullstack Developer"
                        },
                        new
                        {
                            Id = 3,
                            Company = "Amatab",
                            Description = "Management et développement de sites WordPress. Intégration et configuration de plugins (SMTP, WPForms). Hébergement avec Hostinger. Administration et optimisation des environnements Microsoft 365 (SharePoint, Power Apps, Teams).",
                            EndDate = "Novembre 2024",
                            IsCurrent = false,
                            Location = "SFAX, Tunisia",
                            Order = 3,
                            StartDate = "Septembre 2024",
                            Technologies = "WordPress, SMTP, WPForms, Hostinger, Microsoft 365, SharePoint, Power Apps, CRM",
                            Title = "WordPress Developer & Microsoft 365 CRM Maintenance"
                        },
                        new
                        {
                            Id = 4,
                            Company = "Anavid",
                            Description = "Nettoyage de données, gestion d'équipe, analyse de données, annotation et collection de données. Segmentation, SCRUM, Ubuntu.",
                            EndDate = "Juin 2024",
                            IsCurrent = false,
                            Location = "Sfax, Tunisia",
                            Order = 4,
                            StartDate = "Juillet 2023",
                            Technologies = "Python, Data Analysis, Data Cleaning, Segmentation, SCRUM, Microsoft Excel",
                            Title = "Data Analysts Manager"
                        },
                        new
                        {
                            Id = 5,
                            Company = "Anavid",
                            Description = "PFE: Estimation du nombre de personnes dans une foule en utilisant des modèles de deep learning implémentés dans une interface web Flask.",
                            EndDate = "Mai 2023",
                            IsCurrent = false,
                            Location = "Sfax, Sakiet Ezzit, Tunisia",
                            Order = 5,
                            StartDate = "Février 2023",
                            Technologies = "Python, Deep Learning, Flask, Computer Vision",
                            Title = "Intern – Crowd Counting AI"
                        },
                        new
                        {
                            Id = 6,
                            Company = "Optimal Solution",
                            Description = "Développement d'un module de segmentation RFM des clients sous Odoo 15, avec analyse de données, visualisation et Python.",
                            EndDate = "Septembre 2022",
                            IsCurrent = false,
                            Location = "Sahloul/Sousse, Tunisia",
                            Order = 6,
                            StartDate = "Juillet 2022",
                            Technologies = "Odoo 15, Python, Data Analysis, Segmentation, Visualization",
                            Title = "Summer Internship – RFM Segmentation"
                        },
                        new
                        {
                            Id = 7,
                            Company = "ISIMS",
                            Description = "Développement d'une plateforme web avec Laravel. Architecture MVC, modélisation UML, CRUD, Docker.",
                            EndDate = "2022",
                            IsCurrent = false,
                            Location = "Sfax, Tunisia",
                            Order = 7,
                            StartDate = "2022",
                            Technologies = "Laravel, PHP, MVC, UML, CRUD, Docker",
                            Title = "Web Platform Developer (Laravel/PHP)"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Proficiency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = 100,
                            Name = "Arabe",
                            Proficiency = "Langue maternelle"
                        },
                        new
                        {
                            Id = 2,
                            Level = 85,
                            Name = "Français",
                            Proficiency = "Courant"
                        },
                        new
                        {
                            Id = 3,
                            Level = 75,
                            Name = "Anglais",
                            Proficiency = "Intermédiaire avancé"
                        },
                        new
                        {
                            Id = 4,
                            Level = 40,
                            Name = "Allemand",
                            Proficiency = "Notions de base"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GithubUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedinUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Passionate Full-Stack Developer and Software Engineering student with expertise in .NET, Angular, Python, and Odoo. Experienced in ERP development, web platforms, data analysis, and AI/ML solutions. Driven by innovation and committed to building robust, scalable applications.",
                            AvatarUrl = "/assets/avatar.jpg",
                            Email = "abdelgaffaramal@gmail.com",
                            FullName = "Ben Abdelghaffar AMAL",
                            GithubUrl = "https://github.com/amalabdelghaffar",
                            LinkedinUrl = "https://www.linkedin.com/in/amalbenabdelghaffar/",
                            Location = "Sfax, Tunisia",
                            Phone = "21 491 299",
                            Title = "Software Engineering Student | Full-Stack Developer"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Programming Languages",
                            Icon = "devicon-python-plain",
                            Level = 90,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Programming Languages",
                            Icon = "devicon-csharp-plain",
                            Level = 85,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Programming Languages",
                            Icon = "devicon-java-plain",
                            Level = 70,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Programming Languages",
                            Icon = "devicon-php-plain",
                            Level = 75,
                            Name = "PHP"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Programming Languages",
                            Icon = "devicon-c-plain",
                            Level = 65,
                            Name = "C"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Web Development",
                            Icon = "devicon-angularjs-plain",
                            Level = 85,
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Web Development",
                            Icon = "devicon-dotnetcore-plain",
                            Level = 85,
                            Name = "ASP.NET MVC"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Web Development",
                            Icon = "devicon-laravel-plain",
                            Level = 75,
                            Name = "Laravel"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Web Development",
                            Icon = "devicon-flutter-plain",
                            Level = 60,
                            Name = "Flutter"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Web Development",
                            Icon = "devicon-wordpress-plain",
                            Level = 80,
                            Name = "WordPress"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Web Development",
                            Icon = "devicon-html5-plain",
                            Level = 90,
                            Name = "HTML/CSS"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Web Development",
                            Icon = "devicon-javascript-plain",
                            Level = 80,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Web Development",
                            Icon = "devicon-flask-original",
                            Level = 75,
                            Name = "Flask"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Web Development",
                            Icon = "devicon-bootstrap-plain",
                            Level = 85,
                            Name = "Bootstrap"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Artificial Intelligence",
                            Icon = "devicon-tensorflow-original",
                            Level = 75,
                            Name = "TensorFlow"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Artificial Intelligence",
                            Icon = "devicon-opencv-plain",
                            Level = 70,
                            Name = "OpenCV"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Artificial Intelligence",
                            Icon = "fas fa-brain",
                            Level = 75,
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Artificial Intelligence",
                            Icon = "fas fa-network-wired",
                            Level = 70,
                            Name = "Deep Learning"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Tools & Others",
                            Icon = "devicon-git-plain",
                            Level = 85,
                            Name = "Git"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Tools & Others",
                            Icon = "devicon-docker-plain",
                            Level = 70,
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Tools & Others",
                            Icon = "devicon-mysql-plain",
                            Level = 80,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Tools & Others",
                            Icon = "fas fa-chart-bar",
                            Level = 70,
                            Name = "Power BI"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Tools & Others",
                            Icon = "devicon-figma-plain",
                            Level = 65,
                            Name = "Figma"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Tools & Others",
                            Icon = "fas fa-cogs",
                            Level = 85,
                            Name = "Odoo"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Methodology",
                            Icon = "fas fa-tasks",
                            Level = 80,
                            Name = "Scrum/Kanban"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
